apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lsburke12-poi-map-app-dev
  annotations:
    argocd/app-name: lsburke12-poi-map-app-dev
    backstage.io/kubernetes-id: lsburke12-poi-map-app
    backstage.io/kubernetes-namespace: lsburke12
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/lsburke12-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/lsburke12/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/lsburke12/deployments/lsburke12-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/lsburke12-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://lsburke12-poi-map-app-lsburke12.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lsburke12"
  system: workshop-system-lsburke12
  consumesApis:
    - gateway-api-lsburke12
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lsburke12
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lsburke12"
